/*******************************************************************************
 * Copyright (c) 2012-2014 iSphere Project Owners
 * All rights reserved. This program and the accompanying materials 
 * are made available under the terms of the Common Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/cpl-v10.html
 *******************************************************************************/

package biz.isphere.core.versionupdate;

public interface IObsoletePreferences {

    public static final String DE_TASKFORCE_ISPHERE_LIBRARY = "DE.TASKFORCE.ISPHERE.LIBRARY";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_DEFAULT_FORMAT = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.DEFAULT_FORMAT";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_TEXT = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_TEXT";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_TEXT_LIBRARY = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_TEXT.LIBRARY";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_TEXT_COMMAND = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_TEXT.COMMAND";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_HTML = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_HTML";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_HTML_LIBRARY = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_HTML.LIBRARY";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_HTML_COMMAND = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_HTML.COMMAND";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_PDF = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_PDF";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_PDF_LIBRARY = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_PDF.LIBRARY";

    public static final String DE_TASKFORCE_ISPHERE_SPOOLED_FILES_CONVERSION_PDF_COMMAND = "DE.TASKFORCE.ISPHERE.SPOOLED_FILES.CONVERSION_PDF.COMMAND";

    public static final String DE_TASKFORCE_ISPHERE_MESSAGEFILESEARCH_SEARCHSTRING = "DE.TASKFORCE.ISPHERE.MESSAGEFILESEARCH.SEARCHSTRING";

    public static final String DE_TASKFORCE_ISPHERE_SOURCEFILESEARCH_SEARCHSTRING = "DE.TASKFORCE.ISPHERE.SOURCEFILESEARCH.SEARCHSTRING";

}
