     hCopyright('v2.9.3 - xx.xx.xxxx - +
     h           Copyright (c) 2012-xxxx iSphere Project Team')

      /if defined(VERSION_INFO)
     D ISPHERE_SERVER_VERSION...
     D                 c                   '2.9.0'
     D ISPHERE_MIN_CLIENT_VERSION...
     D                 c                   '2.9.0'

     D ISPHERE_DATE...
     D                 c                   'xxxx-xx-xx'
      /endif

