     hCopyright('v3.1.1 - xx.xx.xxxx - +
     h           Copyright (c) 2012-xxxx iSphere Project Team')

      /if defined(VERSION_INFO)
     D ISPHERE_SERVER_VERSION...
     D                 c                   '3.1.1'
     D ISPHERE_MIN_CLIENT_VERSION...
     D                 c                   '3.0.0'

     D ISPHERE_DATE...
     D                 c                   'xxxx-xx-xx'
      /endif

